idf_component_register(
    SRCS
        "main.c"
        "modules/wifi/wifi.c"
        "modules/wifi/dns_server.c"
        "utils/captive_portal/captive_portal.c"
        "modules/wifi/wifi_config_store.c"
        "modules/http_server/http_server.c"
        "modules/filesystem/filesystem.c"
        "modules/system_monitor/system_monitor.c"

    INCLUDE_DIRS
        "."
        "config"
        "modules"
        "modules/wifi"
        "modules/http_server"
        "modules/filesystem"
        "modules/system_monitor"
        "utils/captive_portal"
    REQUIRES
        esp_wifi
        esp_netif
        esp_event
        nvs_flash
        esp_psram
        lwip
        esp_http_server
        littlefs
        spi_flash
)